spring:
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/pokemon
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  servlet:
    context-path: /api