server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: ${DB_PASSWORD:12341234}
    url: jdbc:mysql://localhost:${db.port}/test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
application:
  version: 1.0.2
db:
  port: 3306